landing_html <- function() {
  skip_if_not_installed("shiny")
  library(shiny)
  as.character(landing_page_ui(NS("auth")))
}

test_that("landing is product-first and has no credential fields", {
  html <- landing_html()

  expect_match(html, "Connected evidence for molecular target investigation")
  expect_match(html, "protein,")
  expect_match(html, "genomic, and disease evidence")
  expect_match(html, "Start an investigation")
  expect_match(html, "See how it works")
  expect_match(html, "Already have an account")
  expect_match(html, "How it works")
  expect_match(html, "Sources")
  expect_match(html, "Resolve identities")
  expect_match(html, "Explore evidence")
  expect_match(html, "Compare targets")
  expect_match(html, "Trace provenance")
  expect_match(html, "Create an investigation")
  expect_match(html, "Confirm identities")
  expect_match(html, "Compare candidates")
  expect_match(html, "UniProt")
  expect_match(html, "Ensembl")
  expect_match(html, "Open Targets")
  expect_match(html, "Ready to investigate your targets")
  expect_match(html, "hero-diagram")
  expect_match(html, "hero-demo")
  expect_match(html, "tw-demo")
  expect_match(html, "Confirm molecular identity")
  expect_match(html, "P00533")
  expect_match(html, "ENSG00000146648")
  expect_match(html, "Reactome")
  expect_match(html, "PubMed")
  expect_match(html, "RCSB PDB")
  expect_match(html, "Resolve target")
  expect_match(html, "Non-small-cell lung cancer")
  expect_match(html, "Compare evidence across candidates")
  expect_match(html, "Export research dossier")
  expect_match(html, "Snapshot saved")
  expect_match(html, "workflow preview showing target identity confirmation")
  expect_false(grepl("explainer-svg", html))
  expect_false(grepl("node-hub", html))
  expect_false(grepl("login_email", html))
  expect_false(grepl("register_email", html))
  expect_false(grepl('type="password"', html))
  expect_false(grepl("capability-card", html))
  expect_false(grepl("without creating a custom TargetWeave ranking", html))
  expect_false(grepl("AlphaFold", html))
  expect_false(grepl("join key", html, ignore.case = TRUE))
})

test_that("dedicated auth views open from landing CTAs and return via back", {
  skip_if_not_installed("shiny")
  library(shiny)
  ns <- NS("auth")

  landing <- as.character(public_auth_view_ui("landing", ns))
  sign_in <- as.character(public_auth_view_ui("login", ns))
  register <- as.character(public_auth_view_ui("register", ns))

  expect_match(landing, "Start an investigation")
  expect_false(grepl("Confirm password", landing))

  expect_match(sign_in, ">Sign in<")
  expect_match(sign_in, "login_email")
  expect_match(sign_in, "Show password")
  expect_match(sign_in, "Back to TargetWeave")
  expect_false(grepl("Confirm password", sign_in))

  expect_match(register, "Create account")
  expect_match(register, "register_email")
  expect_match(register, "Confirm password")
  expect_match(register, "Back to TargetWeave")
  expect_false(grepl("Display name", register, ignore.case = TRUE))
  expect_false(grepl("Research role", register, ignore.case = TRUE))
})

test_that("landing product demo uses CSS/JS without network diagram animation", {
  css <- paste(readLines(file.path(app_root(), "www/styles.css")), collapse = "\n")
  js <- paste(readLines(file.path(app_root(), "www/landing.js")), collapse = "\n")
  expect_match(css, "tw-demo")
  expect_match(css, "prefers-reduced-motion")
  expect_false(grepl("explainer-svg", css))
  expect_match(js, "visibilitychange")
  expect_match(js, "prefers-reduced-motion")
  expect_match(js, "MutationObserver")
  expect_match(js, "document.hidden")
  expect_match(js, "TYPE_START_MS")
  expect_match(js, "EGFR")
  ui <- paste(readLines(file.path(app_root(), "R/ui.R")), collapse = "\n")
  expect_match(ui, "landing.js")
})

test_that("panel state helper names researcher-facing retrieval states", {
  html <- as.character(panel_state_ui("retrieving", "Retrieving identity\u2026", "Local to this target."))
  expect_match(html, "panel-state-retrieving")
  expect_match(html, "Retrieving identity")
  expect_match(html, 'role="status"')
})

test_that("static feature constellation remains removed", {
  expect_false(file.exists(file.path(app_root(), "R/modules/mod_product_intro.R")))
  app_src <- paste(readLines(file.path(app_root(), "app.R")), collapse = "\n")
  server_src <- paste(readLines(file.path(app_root(), "R/server.R")), collapse = "\n")
  expect_false(grepl("mod_product_intro", app_src))
  expect_false(grepl("product_intro", server_src))
  expect_match(server_src, "workspace_tour_steps")
})
