build_export_manifest <- function(
  snapshot,
  generated_at = Sys.time(),
  include_notes = TRUE,
  include_researcher = FALSE
) {
  ctx <- snapshot$project_context$model
  statuses <- list(
    overview = export_section_status(snapshot$overview),
    disease_evidence = export_section_status(snapshot$disease_evidence),
    comparison = export_section_status(snapshot$comparison),
    pathways = export_section_status(snapshot$pathways),
    literature = export_section_status(snapshot$literature),
    structures = export_section_status(snapshot$structures)
  )
  sources <- lapply(snapshot$source_manifest %||% list(), function(row) {
    list(
      source = row$source,
      record_id = row$record_id,
      version = row$version %||% row$data_version %||% NA_character_,
      api_version = row$api_version %||% NA_character_,
      retrieved_at = row$retrieved_at,
      cache_status = row$cache_status,
      scope = row$scope,
      query_scope = row$query_scope,
      membership_scope = row$membership_scope,
      disease_query = row$disease_query,
      database_last_update = row$database_last_update
    )
  })
  list(
    dossier_format_version = DOSSIER_FORMAT_VERSION,
    snapshot_id = snapshot$id,
    snapshot_name = snapshot$name,
    snapshot_schema_version = as.integer(snapshot$schema_version %||% SNAPSHOT_SCHEMA_VERSION),
    snapshot_captured_at = format_utc_iso(snapshot$created_at),
    snapshot_captured_at_display = format_user_timestamp(snapshot$created_at),
    export_generated_at = format_utc_iso(generated_at),
    export_generated_at_display = format_user_timestamp(generated_at),
    display_timezone = resolve_display_tz(),
    project_title = ctx$title,
    research_question = ctx$research_question,
    organism = ctx$organism,
    include_notes = isTRUE(include_notes),
    include_researcher = isTRUE(include_researcher),
    section_status = statuses,
    sources = sources
  )
}

export_manifest_text <- function(manifest) {
  lines <- c(
    "TargetWeave research export",
    sprintf("Dossier format version: %s", manifest$dossier_format_version),
    sprintf("Snapshot id: %s", manifest$snapshot_id),
    sprintf("Snapshot name: %s", manifest$snapshot_name),
    sprintf("Snapshot schema version: %s", manifest$snapshot_schema_version),
    sprintf("Snapshot captured at: %s", manifest$snapshot_captured_at_display %||% manifest$snapshot_captured_at),
    sprintf("Export generated at: %s", manifest$export_generated_at_display %||% manifest$export_generated_at),
    sprintf("Display timezone: %s", manifest$display_timezone %||% resolve_display_tz()),
    sprintf("Project title: %s", manifest$project_title),
    sprintf("Research question: %s", manifest$research_question),
    sprintf("Organism: %s", manifest$organism),
    "",
    "Captured sections:"
  )
  for (name in names(manifest$section_status)) {
    lines <- c(lines, sprintf("- %s: %s", name, manifest$section_status[[name]]))
  }
  lines <- c(lines, "", "Sources:")
  for (row in manifest$sources) {
    lines <- c(
      lines,
      sprintf(
        "- %s | id=%s | version=%s | retrieved_at=%s | freshness=%s",
        row$source %||% "",
        row$record_id %||% "",
        row$version %||% row$api_version %||% "",
        row$retrieved_at %||% "",
        row$cache_status %||% ""
      )
    )
  }
  paste(lines, collapse = "\n")
}

export_readme_text <- function() {
  paste(
    c(
      "TargetWeave research export",
      "",
      "This package was generated by TargetWeave from an immutable evidence snapshot.",
      "It is a research record of source data as retrieved at the recorded times.",
      "It is not a clinical recommendation, diagnosis, or treatment suggestion.",
      "",
      "Source data remains attributed to UniProt, Ensembl, Open Targets, Reactome,",
      "NCBI PubMed, and/or RCSB PDB as listed in the manifest.",
      "",
      "Missing sections may mean the evidence was not retrieved or was unavailable",
      "when the snapshot was saved. They do not imply a scientific negative result.",
      "",
      "External URLs (UniProt, PubMed, RCSB, and others) may require a network",
      "connection. Core captured values in report.html and tables/ do not.",
      "",
      "PDF export is not included in this TargetWeave release."
    ),
    collapse = "\n"
  )
}

write_export_manifest_files <- function(dir, manifest) {
  writeLines(export_manifest_text(manifest), file.path(dir, "manifest.txt"))
  writeLines(
    snapshot_json(manifest),
    file.path(dir, "manifest.json")
  )
  writeLines(export_readme_text(), file.path(dir, "README.txt"))
  invisible(dir)
}
